### PR TITLE
Implement create update booking

### PR DESCRIPTION
**Pull request by makskostyshen**
Fuctionality is done

### CODE REVIEW

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [72.74%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[InvalidInterviewerException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInterviewerException.java)|100%|:green_apple:|
|[SlotsAreNotIntersectingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotsAreNotIntersectingException.java)|100%|:green_apple:|
|[InvalidBoundariesException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBoundariesException.java)|100%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|100%|:green_apple:|
|[DurationValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FDurationValidator.java)|100%|:green_apple:|
|[TimeService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FTimeService.java)|100%|:green_apple:|
|[CandidateSlotValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2Fvalidation%2FCandidateSlotValidator.java)|97.87%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|95.69%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|94.74%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|90.32%|:green_apple:|
|[BookingValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2Fvalidation%2FBookingValidator.java)|88.57%|:green_apple:|
|[InterviewerSlot.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlot.java)|79.69%|:green_apple:|
|[BookingDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|46.9%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|41.48%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|30.69%|:green_apple:|
|[BookingService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBookingService.java)|24%|:green_apple:|
|[CandidateController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|8.65%|:x:|
|[InterviewerSlotNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInterviewerSlotNotFoundException.java)|0%|:x:|
|[CandidateSlotNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FCandidateSlotNotFoundException.java)|0%|:x:|
|[InvalidDescriptionException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidDescriptionException.java)|0%|:x:|
|[BookingNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FBookingNotFoundException.java)|0%|:x:|
|[InvalidSubjectException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e5e696092f87245bfdd5c226af72470694226d7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidSubjectException.java)|0%|:x:|

|Total Project Coverage|58.02%|:green_apple:|
|:-|:-:|:-:|

**Review by sonnka — APPROVED** [review]
Looks fine

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [72.63%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[InvalidInterviewerException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInterviewerException.java)|100%|:green_apple:|
|[SlotsAreNotIntersectingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotsAreNotIntersectingException.java)|100%|:green_apple:|
|[InvalidBoundariesException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBoundariesException.java)|100%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|100%|:green_apple:|
|[DurationValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FDurationValidator.java)|100%|:green_apple:|
|[TimeService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FTimeService.java)|100%|:green_apple:|
|[CandidateSlotValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2Fvalidation%2FCandidateSlotValidator.java)|97.87%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|95.69%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|94.74%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|90.32%|:green_apple:|
|[BookingValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2Fvalidation%2FBookingValidator.java)|88.57%|:green_apple:|
|[InterviewerSlot.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlot.java)|79.69%|:green_apple:|
|[BookingDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|46.9%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|41.03%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|30.69%|:green_apple:|
|[BookingService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBookingService.java)|24%|:green_apple:|
|[CandidateController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|8.65%|:x:|
|[InterviewerSlotNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInterviewerSlotNotFoundException.java)|0%|:x:|
|[CandidateSlotNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FCandidateSlotNotFoundException.java)|0%|:x:|
|[InvalidDescriptionException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidDescriptionException.java)|0%|:x:|
|[BookingNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FBookingNotFoundException.java)|0%|:x:|
|[InvalidSubjectException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9528a170c5d63da5b94d527734bda731c80343e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidSubjectException.java)|0%|:x:|

|Total Project Coverage|57.98%|:green_apple:|
|:-|:-:|:-:|

**Review by GrEFeRFeeD — APPROVED** [review]
Great work.

**Review by guzeyarthur — APPROVED** [review]
Good job

**Pull request merged**
