### PR TITLE
Implement role service use logic

### PR DESCRIPTION
**Pull request by guzeyarthur**

### CODE REVIEW

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [59.25%]|:green_apple:|
|:-|:-:|:-:|
|[UserHasAnotherRoleException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/aab40f3605a53b9138290cab8f04a44eb0e9a85a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FUserHasAnotherRoleException.java)|100%|:green_apple:|
|[SelfRevokingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/aab40f3605a53b9138290cab8f04a44eb0e9a85a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSelfRevokingException.java)|100%|:green_apple:|
|[UserNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/aab40f3605a53b9138290cab8f04a44eb0e9a85a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FUserNotFoundException.java)|100%|:green_apple:|
|[UserAlreadyHasRoleException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/aab40f3605a53b9138290cab8f04a44eb0e9a85a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FUserAlreadyHasRoleException.java)|100%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/aab40f3605a53b9138290cab8f04a44eb0e9a85a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|100%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/aab40f3605a53b9138290cab8f04a44eb0e9a85a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|89.83%|:green_apple:|
|[BookingService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/aab40f3605a53b9138290cab8f04a44eb0e9a85a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBookingService.java)|12.5%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/aab40f3605a53b9138290cab8f04a44eb0e9a85a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|8.82%|:x:|
|[Users.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/aab40f3605a53b9138290cab8f04a44eb0e9a85a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FUsers.java)|0%|:x:|
|[EmailDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/aab40f3605a53b9138290cab8f04a44eb0e9a85a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FEmailDto.java)|0%|:x:|

|Total Project Coverage|56.43%|:green_apple:|
|:-|:-:|:-:|

**Review by sashav389 — APPROVED** [review]

**Review by sonnka — APPROVED** [review]
Great work

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [59.25%]|:green_apple:|
|:-|:-:|:-:|
|[UserHasAnotherRoleException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/89a6e211816c2fb2ba5e25e684719a76429cc100/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FUserHasAnotherRoleException.java)|100%|:green_apple:|
|[SelfRevokingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/89a6e211816c2fb2ba5e25e684719a76429cc100/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSelfRevokingException.java)|100%|:green_apple:|
|[UserNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/89a6e211816c2fb2ba5e25e684719a76429cc100/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FUserNotFoundException.java)|100%|:green_apple:|
|[UserAlreadyHasRoleException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/89a6e211816c2fb2ba5e25e684719a76429cc100/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FUserAlreadyHasRoleException.java)|100%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/89a6e211816c2fb2ba5e25e684719a76429cc100/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|100%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/89a6e211816c2fb2ba5e25e684719a76429cc100/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|89.83%|:green_apple:|
|[BookingService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/89a6e211816c2fb2ba5e25e684719a76429cc100/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBookingService.java)|12.5%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/89a6e211816c2fb2ba5e25e684719a76429cc100/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|8.82%|:x:|
|[EmailDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/89a6e211816c2fb2ba5e25e684719a76429cc100/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FEmailDto.java)|0%|:x:|
|[UsersDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/89a6e211816c2fb2ba5e25e684719a76429cc100/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FUsersDto.java)|0%|:x:|

|Total Project Coverage|56.43%|:green_apple:|
|:-|:-:|:-:|

**Review by GrEFeRFeeD — APPROVED** [review]
Good job.

**Pull request merged**
