### PR TITLE
Refactor db

### PR DESCRIPTION
**Pull request by GrEFeRFeeD**

### CODE REVIEW

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [88.84%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/8524fe3e17479b577c8e1c10bbab8b0f951e65d8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/8524fe3e17479b577c8e1c10bbab8b0f951e65d8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|100%|:green_apple:|
|[SecurityConfig.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/8524fe3e17479b577c8e1c10bbab8b0f951e65d8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[CandidateSlotValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/8524fe3e17479b577c8e1c10bbab8b0f951e65d8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2Fvalidation%2FCandidateSlotValidator.java)|97.96%|:green_apple:|
|[CandidateSlot.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/8524fe3e17479b577c8e1c10bbab8b0f951e65d8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlot.java)|92.86%|:green_apple:|
|[CandidateController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/8524fe3e17479b577c8e1c10bbab8b0f951e65d8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|8.65%|:x:|

|Total Project Coverage|56.3%|:green_apple:|
|:-|:-:|:-:|

**Review by guzeyarthur — APPROVED** [review]

**Review by guzeyarthur — APPROVED** [review]

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [88.85%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/45c15339ed2ddd7c3b9d983f0e2557b35ddbc445/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/45c15339ed2ddd7c3b9d983f0e2557b35ddbc445/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|100%|:green_apple:|
|[SecurityConfig.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/45c15339ed2ddd7c3b9d983f0e2557b35ddbc445/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[CandidateSlotValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/45c15339ed2ddd7c3b9d983f0e2557b35ddbc445/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2Fvalidation%2FCandidateSlotValidator.java)|97.98%|:green_apple:|
|[CandidateSlot.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/45c15339ed2ddd7c3b9d983f0e2557b35ddbc445/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlot.java)|92.86%|:green_apple:|
|[CandidateController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/45c15339ed2ddd7c3b9d983f0e2557b35ddbc445/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|8.65%|:x:|

|Total Project Coverage|55.89%|:green_apple:|
|:-|:-:|:-:|

**Review by sonnka — APPROVED** [review]
Good work

**Review by sashav389 — APPROVED** [review]

**Review by makskostyshen — APPROVED** [review]
okay, checked

**Pull request merged**
