### PR TITLE
Refactor candidate slot

### PR DESCRIPTION
**Pull request by guzeyarthur**

### CODE REVIEW

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [63.28%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/08b0ee48af4cf13421a563413b5303d0c9c12588/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|100%|:green_apple:|
|[CandidateSlotValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/08b0ee48af4cf13421a563413b5303d0c9c12588/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2Fvalidation%2FCandidateSlotValidator.java)|98.94%|:green_apple:|
|[CandidateController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/08b0ee48af4cf13421a563413b5303d0c9c12588/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|8.82%|:x:|

|Total Project Coverage|57.56%|:green_apple:|
|:-|:-:|:-:|

**Review by sonnka — APPROVED** [review]

**Review by GrEFeRFeeD — APPROVED** [review]
Okay.

**Review by GrEFeRFeeD — APPROVED** [review]
Fine.

**Review by makskostyshen — APPROVED** [review]
Great job

**Pull request merged**
