### PR TITLE
Implement dashboard

### PR DESCRIPTION
**Pull request by GrEFeRFeeD**

### CODE REVIEW

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [28.75%]|:green_apple:|
|:-|:-:|:-:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/23e58dd9bc854a2b911e75db900c7820bbd8e6b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|94.74%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/23e58dd9bc854a2b911e75db900c7820bbd8e6b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|92.96%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/23e58dd9bc854a2b911e75db900c7820bbd8e6b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|83.58%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/23e58dd9bc854a2b911e75db900c7820bbd8e6b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|41.03%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/23e58dd9bc854a2b911e75db900c7820bbd8e6b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|25.7%|:green_apple:|
|[BookingService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/23e58dd9bc854a2b911e75db900c7820bbd8e6b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBookingService.java)|20%|:green_apple:|
|[DashboardMapDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/23e58dd9bc854a2b911e75db900c7820bbd8e6b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardMapDto.java)|0%|:x:|
|[DashboardInterviewerSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/23e58dd9bc854a2b911e75db900c7820bbd8e6b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardInterviewerSlotDto.java)|0%|:x:|
|[DashboardDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/23e58dd9bc854a2b911e75db900c7820bbd8e6b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardDto.java)|0%|:x:|
|[DashboardCandidateSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/23e58dd9bc854a2b911e75db900c7820bbd8e6b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardCandidateSlotDto.java)|0%|:x:|
|[DashboardBookingDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/23e58dd9bc854a2b911e75db900c7820bbd8e6b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardBookingDto.java)|0%|:x:|

|Total Project Coverage|50.4%|:green_apple:|
|:-|:-:|:-:|

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [35.5%]|:green_apple:|
|:-|:-:|:-:|
|[SecurityConfig.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9315320b2c773af499bb08830e27d0cede48eecf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9315320b2c773af499bb08830e27d0cede48eecf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|94.74%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9315320b2c773af499bb08830e27d0cede48eecf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|92.96%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9315320b2c773af499bb08830e27d0cede48eecf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|83.58%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9315320b2c773af499bb08830e27d0cede48eecf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|41.03%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9315320b2c773af499bb08830e27d0cede48eecf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|25.7%|:green_apple:|
|[BookingService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9315320b2c773af499bb08830e27d0cede48eecf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBookingService.java)|20%|:green_apple:|
|[DashboardMapDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9315320b2c773af499bb08830e27d0cede48eecf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardMapDto.java)|0%|:x:|
|[DashboardInterviewerSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9315320b2c773af499bb08830e27d0cede48eecf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardInterviewerSlotDto.java)|0%|:x:|
|[DashboardDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9315320b2c773af499bb08830e27d0cede48eecf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardDto.java)|0%|:x:|
|[DashboardCandidateSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9315320b2c773af499bb08830e27d0cede48eecf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardCandidateSlotDto.java)|0%|:x:|
|[DashboardBookingDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/9315320b2c773af499bb08830e27d0cede48eecf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardBookingDto.java)|0%|:x:|

|Total Project Coverage|50.5%|:green_apple:|
|:-|:-:|:-:|

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [42.73%]|:green_apple:|
|:-|:-:|:-:|
|[SecurityConfig.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e0b20d3daa86e98bb881d2cdcb150ae327e14aaa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e0b20d3daa86e98bb881d2cdcb150ae327e14aaa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|94.74%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e0b20d3daa86e98bb881d2cdcb150ae327e14aaa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|92.96%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e0b20d3daa86e98bb881d2cdcb150ae327e14aaa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|83.58%|:green_apple:|
|[DashboardBookingDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e0b20d3daa86e98bb881d2cdcb150ae327e14aaa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardBookingDto.java)|73.49%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e0b20d3daa86e98bb881d2cdcb150ae327e14aaa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|41.03%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e0b20d3daa86e98bb881d2cdcb150ae327e14aaa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|25.7%|:green_apple:|
|[BookingService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e0b20d3daa86e98bb881d2cdcb150ae327e14aaa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBookingService.java)|20%|:green_apple:|
|[DashboardMapDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e0b20d3daa86e98bb881d2cdcb150ae327e14aaa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardMapDto.java)|0%|:x:|
|[DashboardInterviewerSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e0b20d3daa86e98bb881d2cdcb150ae327e14aaa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardInterviewerSlotDto.java)|0%|:x:|
|[DashboardDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e0b20d3daa86e98bb881d2cdcb150ae327e14aaa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardDto.java)|0%|:x:|
|[DashboardCandidateSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e0b20d3daa86e98bb881d2cdcb150ae327e14aaa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardCandidateSlotDto.java)|0%|:x:|

|Total Project Coverage|52.38%|:green_apple:|
|:-|:-:|:-:|

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [54.96%]|:green_apple:|
|:-|:-:|:-:|
|[SecurityConfig.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/347e092fec619eaa2a192ae0b063d4027bf7b450/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/347e092fec619eaa2a192ae0b063d4027bf7b450/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|94.74%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/347e092fec619eaa2a192ae0b063d4027bf7b450/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|92.96%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/347e092fec619eaa2a192ae0b063d4027bf7b450/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|83.58%|:green_apple:|
|[DashboardCandidateSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/347e092fec619eaa2a192ae0b063d4027bf7b450/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardCandidateSlotDto.java)|74.56%|:green_apple:|
|[DashboardBookingDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/347e092fec619eaa2a192ae0b063d4027bf7b450/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardBookingDto.java)|73.49%|:green_apple:|
|[DashboardInterviewerSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/347e092fec619eaa2a192ae0b063d4027bf7b450/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardInterviewerSlotDto.java)|65.57%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/347e092fec619eaa2a192ae0b063d4027bf7b450/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|41.03%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/347e092fec619eaa2a192ae0b063d4027bf7b450/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|25.7%|:green_apple:|
|[BookingService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/347e092fec619eaa2a192ae0b063d4027bf7b450/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBookingService.java)|20%|:green_apple:|
|[DashboardMapDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/347e092fec619eaa2a192ae0b063d4027bf7b450/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardMapDto.java)|0%|:x:|
|[DashboardDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/347e092fec619eaa2a192ae0b063d4027bf7b450/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardDto.java)|0%|:x:|

|Total Project Coverage|56.05%|:green_apple:|
|:-|:-:|:-:|

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [62.4%]|:green_apple:|
|:-|:-:|:-:|
|[SecurityConfig.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/06d679cc8e4180f3e507508982b8ed83092237ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/06d679cc8e4180f3e507508982b8ed83092237ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|94.74%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/06d679cc8e4180f3e507508982b8ed83092237ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|92.96%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/06d679cc8e4180f3e507508982b8ed83092237ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|83.58%|:green_apple:|
|[DashboardDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/06d679cc8e4180f3e507508982b8ed83092237ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardDto.java)|79.03%|:green_apple:|
|[DashboardCandidateSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/06d679cc8e4180f3e507508982b8ed83092237ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardCandidateSlotDto.java)|74.56%|:green_apple:|
|[DashboardBookingDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/06d679cc8e4180f3e507508982b8ed83092237ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardBookingDto.java)|73.49%|:green_apple:|
|[DashboardInterviewerSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/06d679cc8e4180f3e507508982b8ed83092237ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardInterviewerSlotDto.java)|65.57%|:green_apple:|
|[DashboardMapDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/06d679cc8e4180f3e507508982b8ed83092237ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardMapDto.java)|45.15%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/06d679cc8e4180f3e507508982b8ed83092237ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|41.03%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/06d679cc8e4180f3e507508982b8ed83092237ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|25.7%|:green_apple:|
|[BookingService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/06d679cc8e4180f3e507508982b8ed83092237ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBookingService.java)|20%|:green_apple:|

|Total Project Coverage|58.34%|:green_apple:|
|:-|:-:|:-:|

**Review by guzeyarthur — APPROVED** [review]

**Review by sashav389 — APPROVED** [review]

**Review by sonnka — APPROVED** [review]

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [61.6%]|:green_apple:|
|:-|:-:|:-:|
|[SecurityConfig.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0dd38a51fe5dacf013f36738dc549371f2f7eb98/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0dd38a51fe5dacf013f36738dc549371f2f7eb98/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|94.74%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0dd38a51fe5dacf013f36738dc549371f2f7eb98/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|85.71%|:green_apple:|
|[DashboardDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0dd38a51fe5dacf013f36738dc549371f2f7eb98/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardDto.java)|79.03%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0dd38a51fe5dacf013f36738dc549371f2f7eb98/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|77.78%|:green_apple:|
|[DashboardCandidateSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0dd38a51fe5dacf013f36738dc549371f2f7eb98/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardCandidateSlotDto.java)|74.56%|:green_apple:|
|[DashboardBookingDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0dd38a51fe5dacf013f36738dc549371f2f7eb98/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardBookingDto.java)|73.49%|:green_apple:|
|[DashboardInterviewerSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0dd38a51fe5dacf013f36738dc549371f2f7eb98/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardInterviewerSlotDto.java)|65.57%|:green_apple:|
|[DashboardMapDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0dd38a51fe5dacf013f36738dc549371f2f7eb98/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FDashboardMapDto.java)|45.15%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0dd38a51fe5dacf013f36738dc549371f2f7eb98/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|40.85%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0dd38a51fe5dacf013f36738dc549371f2f7eb98/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|25.7%|:green_apple:|
|[BookingService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0dd38a51fe5dacf013f36738dc549371f2f7eb98/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBookingService.java)|17.14%|:green_apple:|

|Total Project Coverage|59.29%|:green_apple:|
|:-|:-:|:-:|

**Pull request merged**
