### PR TITLE
Implement coordinator fetures for interviewer slot

### PR DESCRIPTION
**Pull request by sashav389**

### CODE REVIEW

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [40.22%]|:green_apple:|
|:-|:-:|:-:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/fa12d67a8eb8a96a70299febda49d41d3c17d4e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|93.04%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/fa12d67a8eb8a96a70299febda49d41d3c17d4e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|34.67%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/fa12d67a8eb8a96a70299febda49d41d3c17d4e9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|12.5%|:green_apple:|

|Total Project Coverage|56.93%|:green_apple:|
|:-|:-:|:-:|

**Review by sonnka — APPROVED** [review]

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [50.63%]|:green_apple:|
|:-|:-:|:-:|
|[SlotException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d6d1179ba74c23a5c53d988e7dc5f0ad2cc66faf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotException.java)|92.2%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d6d1179ba74c23a5c53d988e7dc5f0ad2cc66faf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|90.3%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d6d1179ba74c23a5c53d988e7dc5f0ad2cc66faf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|35.62%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d6d1179ba74c23a5c53d988e7dc5f0ad2cc66faf/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|12.5%|:green_apple:|

|Total Project Coverage|59.03%|:green_apple:|
|:-|:-:|:-:|

**Review by GrEFeRFeeD — APPROVED** [review]
Good job.

**Review by makskostyshen — APPROVED** [review]
Okay

**Review by makskostyshen — APPROVED** [review]
Okay

**Pull request merged**
