### PR TITLE
Period overlapping bug

### PR DESCRIPTION
**Pull request by makskostyshen**
- Fix bug: periods with the same starting time now overlap
- Refactor: remove OverlapService class and move it's functionality to PeriodService

### CODE REVIEW

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [87.76%]|:green_apple:|
|:-|:-:|:-:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/04dfc35c788f1d95bf3ba2871d01780f03e84e52/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|100%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/04dfc35c788f1d95bf3ba2871d01780f03e84e52/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|100%|:green_apple:|
|[CandidateSlotValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/04dfc35c788f1d95bf3ba2871d01780f03e84e52/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2Fvalidation%2FCandidateSlotValidator.java)|97.94%|:green_apple:|
|[OverlapService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/04dfc35c788f1d95bf3ba2871d01780f03e84e52/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FOverlapService.java)|8.11%|:x:|

|Total Project Coverage|54.5%|:green_apple:|
|:-|:-:|:-:|

**Review by GrEFeRFeeD — APPROVED** [review]
Seems fine.

**Review by guzeyarthur — APPROVED** [review]

**Review by sonnka — APPROVED** [review]
Great work

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [84.98%]|:green_apple:|
|:-|:-:|:-:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d1afc0ccbe22a3ba2d4d77334786f53f3218160d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|100%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d1afc0ccbe22a3ba2d4d77334786f53f3218160d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|100%|:green_apple:|
|[CandidateSlotValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d1afc0ccbe22a3ba2d4d77334786f53f3218160d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2Fvalidation%2FCandidateSlotValidator.java)|97.94%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d1afc0ccbe22a3ba2d4d77334786f53f3218160d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|80.23%|:green_apple:|
|[OverlapService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d1afc0ccbe22a3ba2d4d77334786f53f3218160d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FOverlapService.java)|8.11%|:x:|

|Total Project Coverage|56.2%|:green_apple:|
|:-|:-:|:-:|

**Pull request merged**
