### PR TITLE
:recycle: Add APPLICATION_PORT, DATABASE_PORT, FIRST_COORDINATOR_EMAI…

### PR DESCRIPTION
**Pull request by GrEFeRFeeD**
…L, JWT_VALIDITY environmental variables to docker-compose.yml and application configure. Rename JwtTokenUtil to JwtUtil. Add endpoint for sharing the application facebook client id. Refactor /me endpoint - return CandidateDto in case if user with CANDIDATE role requesting the endpoint.

### CODE REVIEW

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [35.11%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/911251cb9ecfdd40e55c7a4029b7f0d570e4f270/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[SecurityConfig.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/911251cb9ecfdd40e55c7a4029b7f0d570e4f270/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[JwtAuthenticationController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/911251cb9ecfdd40e55c7a4029b7f0d570e4f270/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FJwtAuthenticationController.java)|16.98%|:green_apple:|
|[JwtRequestFilter.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/911251cb9ecfdd40e55c7a4029b7f0d570e4f270/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FJwtRequestFilter.java)|2.73%|:x:|
|[JwtUtil.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/911251cb9ecfdd40e55c7a4029b7f0d570e4f270/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futils%2FJwtUtil.java)|2.63%|:x:|
|[FacebookClientIdDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/911251cb9ecfdd40e55c7a4029b7f0d570e4f270/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FFacebookClientIdDto.java)|0%|:x:|
|[CandidateDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/911251cb9ecfdd40e55c7a4029b7f0d570e4f270/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateDto.java)|0%|:x:|

|Total Project Coverage|51.12%|:green_apple:|
|:-|:-:|:-:|

**Review by sonnka — APPROVED** [review]

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [36.51%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4574760ae8b8e32b2edf4afc0983e83e084a3e1c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[SecurityConfig.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4574760ae8b8e32b2edf4afc0983e83e084a3e1c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[JwtAuthenticationController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4574760ae8b8e32b2edf4afc0983e83e084a3e1c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FJwtAuthenticationController.java)|16.98%|:green_apple:|
|[JwtRequestFilter.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4574760ae8b8e32b2edf4afc0983e83e084a3e1c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FJwtRequestFilter.java)|2.73%|:x:|
|[JwtUtil.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4574760ae8b8e32b2edf4afc0983e83e084a3e1c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futils%2FJwtUtil.java)|2.63%|:x:|
|[FacebookClientIdDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4574760ae8b8e32b2edf4afc0983e83e084a3e1c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FFacebookClientIdDto.java)|0%|:x:|
|[CandidateDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4574760ae8b8e32b2edf4afc0983e83e084a3e1c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateDto.java)|0%|:x:|

|Total Project Coverage|54.55%|:green_apple:|
|:-|:-:|:-:|

**Review by makskostyshen — APPROVED** [review]
okay

**Review by makskostyshen — APPROVED** [review]

**Comment by GrEFeRFeeD** [comment]
|File|Coverage [22.79%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/f638870012adcbe68774ab2ee98e5f4f5839044b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[SecurityConfig.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/f638870012adcbe68774ab2ee98e5f4f5839044b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[JwtAuthenticationController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/f638870012adcbe68774ab2ee98e5f4f5839044b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FJwtAuthenticationController.java)|14.88%|:green_apple:|
|[JwtRequestFilter.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/f638870012adcbe68774ab2ee98e5f4f5839044b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FJwtRequestFilter.java)|2.73%|:x:|
|[JwtUtil.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/f638870012adcbe68774ab2ee98e5f4f5839044b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futils%2FJwtUtil.java)|2.63%|:x:|
|[FacebookUtil.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/f638870012adcbe68774ab2ee98e5f4f5839044b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futils%2FFacebookUtil.java)|0.99%|:x:|
|[FacebookOauthInfoDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/f638870012adcbe68774ab2ee98e5f4f5839044b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FFacebookOauthInfoDto.java)|0%|:x:|
|[CandidateDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/f638870012adcbe68774ab2ee98e5f4f5839044b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateDto.java)|0%|:x:|

|Total Project Coverage|54.15%|:green_apple:|
|:-|:-:|:-:|

**Review by sashav389 — APPROVED** [review]

**Pull request merged**
