### PR TITLE
Docker initial containerization

### PR DESCRIPTION
**Pull request by makskostyshen**

### CODE REVIEW

**Comment by GrEFeRFeeD** [comment]
> There is no coverage information present for the Files changed

|Total Project Coverage|54.99%|:green_apple:|
|:-|:-:|:-:|

**Review by sonnka — APPROVED** [review]

**Review by GrEFeRFeeD — APPROVED** [review]
Good job.

**Review by sashav389 — APPROVED** [review]
nice work

**Comment by GrEFeRFeeD** [comment]
> There is no coverage information present for the Files changed

|Total Project Coverage|54.99%|:green_apple:|
|:-|:-:|:-:|

**Pull request merged**
